// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiarwtalftwhxjrlzovu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpYXJ3dGFsZnR3aHhqcmx6b3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1ODc0MTEsImV4cCI6MjA1NzE2MzQxMX0.nN8i0s31uqgkiZ3KIj0Ll2jvAcN2-hfUPmFRygtiZPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);